# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcppd-storage
spec:
  storageClassName: standard
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mongo-data-disk
    fsType: ext4
